[project]
name = "env-ssl-wrapper"
version = "0.4.0"
description = "One torch-native interface for any MDP environment"
authors = [
    { name = "Phil Wang", email = "lucidrains@gmail.com" }
]
readme = "README.md"
requires-python = ">= 3.10"
license = { file = "LICENSE" }
keywords = [
    'artificial intelligence',
    'deep learning',
    'self supervised learning',
    'reinforcement learning'
]

classifiers=[
    'Development Status :: 4 - Beta',
    'Intended Audience :: Developers',
    'Topic :: Scientific/Engineering :: Artificial Intelligence',
    'License :: OSI Approved :: MIT License',
    'Programming Language :: Python :: 3.10',
]

dependencies = [
    "discrete-continuous-embed-readout",
    "einx>=0.3.0",
    "einops>=0.8.1",
    "memmap-replay-buffer",
    "torch>=2.5",
    "torch-einops-utils>=0.0.29",
    "x-transformers",
    "x-mlps-pytorch",
]

[project.urls]
Homepage = "https://pypi.org/project/env-ssl-wrapper/"
Repository = "https://codeberg.org/lucidrains/env-ssl-wrapper"

[project.optional-dependencies]
examples = [
    "fire",
]
test = [
    "pytest",
    "gymnasium>=0.29.1",
    "box2d-py>=2.3.5",
    "gymnasium-robotics",
    "mujoco",
    "dm-control",
    "pybullet",
    "pygame",
    "pillow",
    "imageio",
    "populora",
]

[tool.pytest.ini_options]
pythonpath = [
    "."
]
testpaths = [
    "tests"
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build]
include = [
    "env_ssl_wrapper",
    "pyproject.toml",
    "README.md",
    "LICENSE"
]

[tool.hatch.build.targets.wheel]
packages = ["env_ssl_wrapper"]
